version: '3.9'
services:

    es8:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
        container_name: es8
        environment:
            - node.name=es8
            - cluster.name=es-docker-cluster
            - discovery.type=single-node
            - xpack.security.enabled=false
        volumes:
            - data:/usr/share/elasticsearch/data
        ports:
            - 9200:9200
        networks:
            - app-network

    kib8:
        image: docker.elastic.co/kibana/kibana:8.16.1
        container_name: kib8
        environment:
            - node.name=kib8
            - cluster.name = es-docker-cluster
            - ELASTICSEARCH_HOSTS=http://es8:9200
        ports:
            - 5601:5601
        networks:
            - app-network
        depends_on:
            - es8
 

    fastapi-app:
        build: 
            context: ./fastapi
        ports:
            - 8000:8000
        networks: 
            - app-network
        depends_on:
            - es8

    flask-app:
        build: 
            context: ./flask
        ports: 
            - 5000:5000
        networks:
            - app-network
        depends_on:
            - fastapi-app

 
volumes: 
      data: 
        driver: local
networks:
    app-network:
        driver: bridge