name: Docker Compose Workflow

on: [push]

jobs:

  unit-test:
    runs-on: ubuntu-latest
    steps:

    - name: checkout code
      uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install flask
          pip install fastapi
          pip install pytest

    - name: Run tests
      run: |
        pytest

  build-and-publish-images:
    needs: unit-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push flask image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./src/flask/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flask-app:latest

    - name: Build and push fastAPI image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./src/fastapi/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/fastapi-app:latest

  build-docker-compose:
    needs: build-and-publish-images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    
      - name: Run Docker Compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./src/docker-compose.yml"
